name: github-assign
description: Automate assigns

runs:

  using: composite
  steps:
    - name: Run add assignee
      run: |
        curl -X POST -H 'authorization: Bearer ${{ github.token }}' \
          -d '{"assignees": ["${{ github.event.pull_request.user.login }}"]}' \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees
      shell: bash
