name: review-thanks
description: Remove label when closed PR

inputs:

  remove-labels:
    description: 'Labels list for pull request (comma-separated string), Defaults to "review"'
    required: false
    default: "review"

runs:

  using: composite
  steps:
    - name: Remove review labels
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh pr edit ${{ github.event.pull_request.number }} \
          --repo ${{ github.repository }} \
          --remove-label "${{ inputs.remove-labels }}"
      shell: bash
