name: yarn upgrade
description: Upgrade yarn package by ci-yarn-upgrade

inputs:

  github-user-name:
    description: Commit author name, Defaults to github-actions[bot]
    required: false
    default: github-actions[bot]

  github-user-email:
    description: Commit author email, Defaults to github-actions[bot]@users.noreply.github.com
    required: false
    default: github-actions[bot]@users.noreply.github.com

  options:
    description: CLI options, Defaults to blank
    required: false
    default: ""

runs:

  using: composite
  steps:
    - name: Install ci-yarn-upgrade
      run: sudo yarn global add ci-yarn-upgrade
      shell: bash

    - name: Run ci-yarn-upgrade
      env:
        GITHUB_ACCESS_TOKEN: ${{ github.token }}
        GIT_USER_NAME: ${{ inputs.github-user-name }}
        GIT_USER_EMAIL: ${{ inputs.github-user-email }}
      run: ci-yarn-upgrade --execute --keep ${{ inputs.options }}
      shell: bash
