name: get-pull-request
description: Get pull request

inputs:

  pull-number:
    description: Pull request number
    required: true

outputs:

  head-ref:
    description: Head branch name in Pull request
    value: ${{ steps.get-pull-request.outputs.head_ref }}

  base-ref:
    description: Base branch name in Pull request
    value: ${{ steps.get-pull-request.outputs.base_ref }}

  pull-request:
    description: Pull request by json format
    value: ${{ steps.get-pull-request.outputs.response }}

runs:

  using: composite
  steps:
    - name: Get pull request
      run: |
        res=$(curl -X GET -H "authorization: Bearer ${{ github.token }}" \
                https://api.github.com/repos/${{ github.repository }}/pulls/${{ inputs.pull-number }})

        echo "::set-output name=head_ref::$(echo "$res" | jq -r .head.ref)"
        echo "::set-output name=base_ref::$(echo "$res" | jq -r .base.ref)"
        echo "::set-output name=response::$(echo "$res" | tr -d '\n')"
      id: get-pull-request
      shell: bash
