name: github-reviewers
description: Send slack message when assigned pull request reviewers

inputs:

  slack-webhook-url:
    description: Slack Webhook URL
    required: true

  message:
    description: Slack message, Defaults to "レビューお願いします :pray:"
    required: false
    default: "レビューお願いします :pray:"

  message-color:
    description: Slack message attachments color, Defaults to "#000000"
    required: false
    default: "#000000"

runs:

  using: composite
  steps:
    - name: Set query value
      run: |
        # レビュアリクエストがあった時刻から10秒前の時刻を取得
        from_datetime=$(ruby -rtime -e 'puts (Time.parse("${{ github.event.pull_request.updated_at }}") - 10).strftime("%FT%TZ")')
        echo "from-datetime=${from_datetime}" >> $GITHUB_OUTPUT
      id: query-value
      shell: bash

    - name: Get reviewers
      env:
        GH_TOKEN: ${{ github.token }}
        REQUEST_BODY: |
          query {
            node(id: "${{ github.event.pull_request.node_id }}") {
              ... on PullRequest {
                timelineItems(itemTypes: [REVIEW_REQUESTED_EVENT], since: "${{ steps.query-value.outputs.from-datetime }}", first: 100) {
                  nodes { ... on ReviewRequestedEvent { requestedReviewer { ... on User { login } } } }
                }
              }
            }
          }
      run: |
        # レビュアにアサインされたユーザを取得
        reviewers=($(gh api graphql -f query="${REQUEST_BODY}" | jq -r '.data.node.timelineItems.nodes[].requestedReviewer.login' | awk '{print "@"$0}'))
        echo "reviewers=${reviewers[@]}" >> $GITHUB_OUTPUT

        # レビュアリクエストがあった時刻をUNIXTIMEに変換
        event_time=$(ruby -rtime -e 'puts Time.parse("${{ github.event.pull_request.updated_at }}").to_i')
        echo "event-time=${event_time}" >> $GITHUB_OUTPUT
      id: get-reviewers
      shell: bash

    - name: Send message
      env:
        MESSAGE: |
          {
            "attachments": [{
              "title": "#${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}",
              "title_link": "${{ github.event.pull_request.html_url }}",
              "text": "${{ steps.get-reviewers.outputs.reviewers }}\n${{ inputs.message }}",
              "footer": "<${{ github.event.repository.html_url }}|${{ github.repository }}>",
              "footer_icon": "https://slack.github.com/static/img/favicon-neutral.png",
              "ts": ${{ steps.get-reviewers.outputs.event-time }},
              "color": "${{ inputs.message-color }}"
            }]
          }
      run: echo ${MESSAGE} | curl -X POST ${{ inputs.slack-webhook-url }} -d @-
      shell: bash
