name: delete branch
description: Delete branch using REST API

runs:

  using: composite
  steps:
    - name: Delete branch
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        count=$(gh pr list --repo ${{ github.repository }} --head ${{ github.head_ref }} --state open --json number --jq 'length')
        if [[ ${count} == 0 ]]; then
          gh api -X DELETE repos/${{ github.repository }}/git/refs/heads/${{ github.head_ref }}
        fi
      shell: bash
