name: github-issue-comment-reaction
description: Automate add reaction by issue comment

inputs:

  reaction-type:
    description: Reaction type, Defaults to eyes
    required: false
    default: eyes

runs:

  using: composite
  steps:
    - name: Add reaction
      run: |
        curl -X POST -H "authorization: Bearer ${{ github.token }}" \
          -H "Accept: application/vnd.github.squirrel-girl-preview+json" \
          -d '{"content": "${{ inputs.reaction-type }}"}' \
          https://api.github.com/repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions
      shell: bash
